#!/bin/bash

CWD=$PWD

# DIR=/home/torsten/ASP/asprilo/instances/tiny_cases/4x4c/warehouse_x4_y4_n16_r3_s6_ps2_pr6_u12_o0_N50/merged
DIR=/home/torsten/ASP/asprilo/instances/standard_cases/4/warehouse_x10_y10_n100_r4_s12_ps3_pr3_u20_o0_N1/merged

# SCALL="clingo   action-MPP-3.ilp goal-D-0.ilp  --stats"                    # benchme-MPP-3-ilp-D-0-ilp
SCALL="clingcon   action-MPP-3.iclp goal-D-0.iclp  --stats"                    # benchme-MPP-3-iclp-D-0-iclp
# SCALL="clingo   action-MPP-3.ilp goal-D-r.ilp  --stats"                    # benchme-MPP-3-ilp-D-r-ilp
# SCALL="clingo   action-MPP-3.ilp goal-D-q.ilp  --stats"                    # benchme-MPP-3-ilp-D-q-ilp
# SCALL="clingcon action-MPP-3.ilp goal-D-q.iclp --stats"                    # benchme-MPP-3-ilp-D-q-iclp
#
# SCALL="clingcon action-MPP-3.ilp goal-D-r.ilp strategy-MPP-3.ilp --stats"  # benchme-MPP-3-ilp-D-r-ilp-strategy
LOG="BENCH"

for f in $DIR/*.lp
do
CALL="$SCALL $f"
echo $CALL
# echo $CALL >>$LOG.out 2>>$Log.err
$CALL
done

